use springit;

drop table  if exists VOTE;
CREATE TABLE VOTE(ID BIGINT NOT NULL,VOTE INTEGER NOT NULL);

SET SQL_MODE='ALLOW_INVALID_DATES';

CREATE  TABLE LINK(
    ID BIGINT NOT NULL,
    CREATED_BY VARCHAR(255),
    CREATION_DATE TIMESTAMP,
    LAST_MODIFIED_BY VARCHAR(255),
    LAST_MODIFIED_DATE timestamp,
    TITLE VARCHAR(255),
    URL VARCHAR(255)
);


CREATE  TABLE COMMENT(
    ID BIGINT NOT NULL,
    BODY VARCHAR(255),
    CREATED_BY VARCHAR(255),
    CREATION_DATE TIMESTAMP,
    LAST_MODIFIED_BY VARCHAR(255),
    LAST_MODIFIED_DATE TIMESTAMP,
    LINK_ID BIGINT
);





